variables:
- name: major
  value: '2'
- name: minor
  value: '1911'
- name: extensionName
  value: 'banner-settings-hub'
- name: marketplaceServiceConnection
  value: 'marketplaceServiceConnection'
- name: publisherId
  value: 'ms-devlabs'
- name: publicExtensionName
  value: "Banner Settings"

name: $(major).$(minor)$(rev:.r)

pool:
  vmImage: 'vs2017-win2016'

trigger:
  branches:
    include:
    - main

pr: none

resources:
  repositories:
    - repository: pipeline-templates
      type: git
      name: DevLabs Extensions/pipeline-templates
      ref: main

stages:
- stage: 'Build'
  jobs:
  - job: 'BuildPack'
    displayName: "Build and package"
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - template: build.yml@pipeline-templates
      parameters:
        workingDirectory: '$(Build.SourcesDirectory)'

#    - template: package.yml@pipeline-templates
#      parameters:
#        extensionName: $(extensionName)
#        outputPath: 'out'
#        rootPath: '$(Build.SourcesDirectory)'

    - task: TfxInstaller@5
      inputs:
        version: 'builtin'

    - script: |
        tfx extension create --manifests ./ado-manifests/azure-devops-extension-base.json --overrides-file ./ado-manifests/azure-devops-extension-dev.json
      displayName: 'Package development extension'

    - script: |
        tfx extension create --manifests ./ado-manifests/azure-devops-extension-base.json --overrides-file ./ado-manifests/azure-devops-extension-prod.json
      displayName: 'Package extension'

#    - script: |
#        npm run package:prod
#      displayName: 'Package (prod)'

- stage: 'DeployDev'
  displayName: 'Deploy to dev'
  dependsOn: Build
  condition: succeeded()
  jobs: 
  - template: deploy.yml@pipeline-templates
    parameters:
      environment: 'dev'
      extensionName: $(extensionName)
      marketplaceConnectedServiceName: $(marketplaceServiceConnection)
      publisherId: $(publisherId)
      publicExtensionName: $(publicExtensionName)
      updateTaskVersion: true

- stage: 'DeployTest'
  displayName: 'Deploy to Test'
  dependsOn: DeployDev
  condition: succeeded()
  jobs:
  - template: deploy.yml@pipeline-templates
    parameters:
      environment: 'test'
      extensionName: $(extensionName)
      marketplaceConnectedServiceName: $(marketplaceServiceConnection)
      publisherId: $(publisherId)
      publicExtensionName: $(publicExtensionName)
      updateTaskVersion: true

- stage: 'DeployRelease'
  displayName: 'Deploy Release'
  dependsOn: DeployTest
  condition: succeeded()
  jobs:
  - template: deploy.yml@pipeline-templates
    parameters:
      environment: 'public'
      extensionName: $(extensionName)
      marketplaceConnectedServiceName: $(marketplaceServiceConnection)
      publisherId: $(publisherId)
      publicExtensionName: $(publicExtensionName)
      extensionVisibility: 'public'
      updateTaskVersion: true
